indyRP2:
    EndEffector:
        position: [0, 0, 0.0605]
        orientation: [0, 0, 0]
    JointInfo:
        RobotBaseJoint: []
        RobotMovableJoint: [0, 1, 2, 3, 4, 5, 6]
        RobotEEJoint: []

indyRP2_handle:
    EndEffector:
        position: [0, 0, 0.1525]
        orientation: [0, 0, 0]
    JointInfo:
        RobotBaseJoint: []
        RobotMovableJoint: [0, 1, 2, 3, 4, 5, 6]
        RobotEEJoint: []