franka_panda:
    EndEffector:
        position: [0, 0, 0.1070]
        orientation: [0, 0, 0]
    Mobile:
        valid: false
    JointInfo:
        RobotBaseJoint: []
        RobotMovableJoint: [0, 1, 2, 3, 4, 5, 6]
        RobotEEJoint: [7]
        RobotFTJoint: []
        GripperJoint: []

franka_panda_stick:
    EndEffector:
        position: [0, 0, 0.3870]
        orientation: [180, 0, 0]
    Mobile:
        valid: false
    JointInfo:
        RobotBaseJoint: []
        RobotMovableJoint: [0, 1, 2, 3, 4, 5, 6]
        RobotEEJoint: []
        RobotFTJoint: [7]
        GripperJoint: []

franka_panda_handle:
    EndEffector:
        position: [0, 0, 0.1955]
        orientation: [0, 0, 0]
    Mobile:
        valid: false
    JointInfo:
        RobotBaseJoint: []
        RobotMovableJoint: [0, 1, 2, 3, 4, 5, 6]
        RobotEEJoint: []
        RobotFTJoint: [7]
        GripperJoint: []

franka_panda_gripper:
    EndEffector:
        position: [0, 0, 0.21]
        orientation: [0, 0, -45]
    Mobile:
        valid: false
    JointInfo:
        RobotBaseJoint: []
        RobotMovableJoint: [0, 1, 2, 3, 4, 5, 6]
        RobotEEJoint: []
        RobotFTJoint: [7]
        GripperJoint: [8, 9]

franka_panda_YDC:
    EndEffector:
        position: [0, 0, 0.2904]
        orientation: [0, 0, -45]
    Mobile:
        valid: false
    JointInfo:
        RobotBaseJoint: []
        RobotMovableJoint: [0, 1, 2, 3, 4, 5, 6]
        RobotEEJoint: []
        RobotFTJoint: [7]
        GripperJoint: [8, 9]